# Generated by Django 5.1.3 on 2024-11-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_comment_uuid_issue_assigned_to_issue_nature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
