# Generated by Django 5.1.3 on 2024-11-22 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_project_created_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='creator',
            new_name='created_by',
        ),
    ]
